name: wog_app
description: "Word of God - Integrated App"
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Ivi thappakunda undali:
  xml: ^6.5.0
  share_plus: ^10.1.4
  google_fonts: ^6.2.1
  firebase_core: ^3.1.0
  cloud_firestore: ^5.0.0
  firebase_auth: ^5.1.0
  firebase_storage: ^12.0.0
  http: ^1.1.0
  audioplayers: ^5.2.1
  google_sign_in: ^6.2.1
  google_fonts: ^6.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/bible.xml
